### ISSUE TITLE
Mekanism/TE startup crash after update to W-NC

### ISSUE THREAD

**Issue by ftog-thorgal** [BevoTechPack/BevoTechPack#1021]
Bevo Tech Pack Version :- Update from V-NC to W-NC

When we try to update the server to W-NC it won't start with the following error:

Time: 7/11/16 3:45 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at mekanism.generators.common.tile.turbine.TileEntityTurbineValve.fill(TileEntityTurbineValve.java:363)
	at cofh.thermaldynamics.duct.fluid.TileFluidDuct.transfer(TileFluidDuct.java:141)
	at cofh.thermaldynamics.duct.fluid.TileFluidDuct.tickPass(TileFluidDuct.java:82)
	at cofh.thermaldynamics.duct.fluid.TileFluidDuctFlux.tickPass(TileFluidDuctFlux.java:86)
	at cofh.thermaldynamics.duct.fluid.FluidGrid.tickGrid(FluidGrid.java:133)
	at cofh.thermaldynamics.core.WorldGridList.tickEnd(WorldGridList.java:63)
	at cofh.thermaldynamics.core.TickHandler.tick(TickHandler.java:91)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_968_TickHandler_tick_WorldTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:260)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:974)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
	at java.lang.Thread.run(Unknown Source)

**Comment by b0bst3r** [comment]
Duplicate https://github.com/BevoTechPack/BevoTechPack/issues/1020 I know about it, Mekanism has already fixed it just waiting for a release.
