### ISSUE TITLE
Using /help leads to crash

### ISSUE THREAD

**Issue by pures** [BevoTechPack/BevoTechPack#1025]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :-  BTP-Reborn-BetaV-NC
### Description of issue/bug

This is from a fresh install, I've never used this pack before.  It's the only pack I have for ATLauncher.
Using /help about 4 consecutive times leads to a crash.  After I crashed it a few times, when I ran /help it would only give me an error.
### Steps to reproduce the issue/bug

type:
/help 1
/help 2
/help 3
/help 4 _Crash_

or try
/help 2
/help 3
/help 4
/help 5 _Crash_
### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

http://pastebin.com/WSJVDQhn

Questions:

Did you add any additional mods? - No
Do you use optifine? - No
Did the problem appear in single player or on a server? - Single, haven't tried server.

**Comment by pures** [comment]
Hello,
I seem to have found a cause and fix:  http://minecraft.curseforge.com/projects/helpfixer

Here's the errorlog from ATLauncher: 23/7/2016 23:50:49 PM] [Server thread/ERROR]: Couldn't process command: 'help'
[23/7/2016 23:50:49 PM] java.lang.IllegalArgumentException: Comparison method violates its general contract!
[23/7/2016 23:50:49 PM] 	at java.util.ComparableTimSort.mergeLo(Unknown Source) ~[?:1.8.0_101]
[23/7/2016 23:50:49 PM] 	at java.util.ComparableTimSort.mergeAt(Unknown Source) ~[?:1.8.0_101]
[23/7/2016 23:50:49 PM] 	at java.util.ComparableTimSort.mergeForceCollapse(Unknown Source) ~[?:1.8.0_101]
[23/7/2016 23:50:49 PM] 	at java.util.ComparableTimSort.sort(Unknown Source) ~[?:1.8.0_101]
[23/7/2016 23:50:49 PM] 	at java.util.Arrays.sort(Unknown Source) ~[?:1.8.0_101]
[23/7/2016 23:50:49 PM] 	at java.util.Arrays.sort(Unknown Source) ~[?:1.8.0_101]
[23/7/2016 23:50:49 PM] 	at java.util.ArrayList.sort(Unknown Source) ~[?:1.8.0_101]
[23/7/2016 23:50:49 PM] 	at java.util.Collections.sort(Unknown Source) ~[?:1.8.0_101]
[23/7/2016 23:50:49 PM] 	at net.minecraft.command.CommandHelp.func_71534_d(SourceFile:84) ~[au.class:?]
[23/7/2016 23:50:49 PM] 	at net.minecraft.command.CommandHelp.func_71515_b(SourceFile:38) ~[au.class:?]
[23/7/2016 23:50:49 PM] 	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
[23/7/2016 23:50:49 PM] 	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
[23/7/2016 23:50:49 PM] 	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
[23/7/2016 23:50:49 PM] 	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
[23/7/2016 23:50:49 PM] 	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
[23/7/2016 23:50:49 PM] 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
[23/7/2016 23:50:49 PM] 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
[23/7/2016 23:50:49 PM] 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
[23/7/2016 23:50:49 PM] 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]

**Comment by b0bst3r** [comment]
Yeah without helpfixer /help in ssp just brings up an in game error message.  Guess flaxbeards is doing something to /help which is causing helpfixer to crash.

**Comment by ranger135xp** [comment]
@BevoLJ you should add HelpFixer to this modpack. I'm using the latest 1.0.7 with this pack.

**Comment by Jimmio92** [comment]
This is still an issue as of 20170906. The process for help just dies instantly. I get no output on the server, and running it from in game as my player causes a disconnect crash. I have no idea what commands I can use, help me get help Dx
