### ISSUE TITLE
I cant start the pack it crash every time

### ISSUE THREAD

**Issue by yannickfelle** [BevoTechPack/BevoTechPack#1028]
[24/7/2016 02:12:46 AM] Console Cleared
[24/7/2016 02:12:48 AM] Logging into Minecraft!
[24/7/2016 02:12:48 AM] Trying to login with access token!
[24/7/2016 02:12:49 AM] Launching pack Bevo's Tech Pack BTP-Reborn-BetaW-NC for Minecraft 1.7.10
[24/7/2016 02:12:49 AM] Launching Minecraft with the following arguments (user related stuff has been removed): [C:\Program Files\Java\jre1.8.0_101\bin\javaw, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -XX:-OmitStackTraceInFastThrow, -XX:+UseConcMarkSweepGC, -XX:+CMSIncrementalMode, -XX:-UseAdaptiveSizePolicy, -Xms256M, -Xmx3584M, -XX:MetaspaceSize=256M, -Duser.language=en, -Duser.country=US, -Dfml.log.level=INFO, -Djava.library.path=**USERSDIR**\Instances\BevosTechPack1\bin\natives, -cp, **USERSDIR**\ATLauncher.exe;anything;**USERSDIR**\Instances\BevosTechPack1\jarmods\forge-1.7.10-10.13.4.1566-1.7.10-universal.jar;**USERSDIR**\Instances\BevosTechPack1\bin\akka-actor_2.11-2.3.3.jar;**USERSDIR**\Instances\BevosTechPack1\bin\asm-all-5.0.3.jar;**USERSDIR**\Instances\BevosTechPack1\bin\commons-lang3-3.3.2.jar;**USERSDIR**\Instances\BevosTechPack1\bin\config-1.2.1.jar;**USERSDIR**\Instances\BevosTechPack1\bin\guava-17.0.jar;**USERSDIR**\Instances\BevosTechPack1\bin\jopt-simple-4.5.jar;**USERSDIR**\Instances\BevosTechPack1\bin\launchwrapper-1.12.jar;**USERSDIR**\Instances\BevosTechPack1\bin\lzma-0.0.1.jar;**USERSDIR**\Instances\BevosTechPack1\bin\scala-actors-migration_2.11-1.1.0.jar;**USERSDIR**\Instances\BevosTechPack1\bin\scala-compiler-2.11.1.jar;**USERSDIR**\Instances\BevosTechPack1\bin\scala-continuations-library_2.11-1.0.2.jar;**USERSDIR**\Instances\BevosTechPack1\bin\scala-continuations-plugin_2.11.1-1.0.2.jar;**USERSDIR**\Instances\BevosTechPack1\bin\scala-library-2.11.1.jar;**USERSDIR**\Instances\BevosTechPack1\bin\scala-parser-combinators_2.11-1.0.1.jar;**USERSDIR**\Instances\BevosTechPack1\bin\scala-reflect-2.11.1.jar;**USERSDIR**\Instances\BevosTechPack1\bin\scala-swing_2.11-1.0.1.jar;**USERSDIR**\Instances\BevosTechPack1\bin\scala-xml_2.11-1.0.2.jar;**USERSDIR**\Instances\BevosTechPack1\bin\netty-1.6.jar;**USERSDIR**\Instances\BevosTechPack1\bin\realms-1.3.5.jar;**USERSDIR**\Instances\BevosTechPack1\bin\commons-compress-1.8.1.jar;**USERSDIR**\Instances\BevosTechPack1\bin\httpclient-4.3.3.jar;**USERSDIR**\Instances\BevosTechPack1\bin\commons-logging-1.1.3.jar;**USERSDIR**\Instances\BevosTechPack1\bin\httpcore-4.3.2.jar;**USERSDIR**\Instances\BevosTechPack1\bin\vecmath-1.3.1.jar;**USERSDIR**\Instances\BevosTechPack1\bin\trove4j-3.0.3.jar;**USERSDIR**\Instances\BevosTechPack1\bin\icu4j-core-mojang-51.2.jar;**USERSDIR**\Instances\BevosTechPack1\bin\codecjorbis-20101023.jar;**USERSDIR**\Instances\BevosTechPack1\bin\codecwav-20101023.jar;**USERSDIR**\Instances\BevosTechPack1\bin\libraryjavasound-20101123.jar;**USERSDIR**\Instances\BevosTechPack1\bin\librarylwjglopenal-20100824.jar;**USERSDIR**\Instances\BevosTechPack1\bin\soundsystem-20120107.jar;**USERSDIR**\Instances\BevosTechPack1\bin\netty-all-4.0.10.Final.jar;**USERSDIR**\Instances\BevosTechPack1\bin\commons-io-2.4.jar;**USERSDIR**\Instances\BevosTechPack1\bin\commons-codec-1.9.jar;**USERSDIR**\Instances\BevosTechPack1\bin\jinput-2.0.5.jar;**USERSDIR**\Instances\BevosTechPack1\bin\jutils-1.0.0.jar;**USERSDIR**\Instances\BevosTechPack1\bin\gson-2.2.4.jar;**USERSDIR**\Instances\BevosTechPack1\bin\authlib-1.5.21.jar;**USERSDIR**\Instances\BevosTechPack1\bin\log4j-api-2.0-beta9.jar;**USERSDIR**\Instances\BevosTechPack1\bin\log4j-core-2.0-beta9.jar;**USERSDIR**\Instances\BevosTechPack1\bin\lwjgl-2.9.1.jar;**USERSDIR**\Instances\BevosTechPack1\bin\lwjgl_util-2.9.1.jar;**USERSDIR**\Instances\BevosTechPack1\bin\twitch-5.16.jar;**USERSDIR**\Instances\BevosTechPack1\bin\minecraft.jar, net.minecraft.launchwrapper.Launch, --username, REDACTED, --version, 1.7.10, --gameDir, **USERSDIR**\Instances\BevosTechPack1, --assetsDir, **USERSDIR**\Configs\Resources, --assetIndex, 1.7.10, --uuid, 6d648c206073454eb50cebb810662645, --accessToken, REDACTED, --userProperties, REDACTED, --userType, mojang, --width=854, --height=480, --tweakClass=cpw.mods.fml.common.launcher.FMLTweaker]
[24/7/2016 02:12:49 AM] 2016-07-24 02:12:49,395 ERROR Error processing element Queue: CLASS_NOT_FOUND
[24/7/2016 02:12:49 AM] 2016-07-24 02:12:49,416 ERROR Unable to locate appender ServerGuiConsole for logger com.mojang
[24/7/2016 02:12:49 AM] 2016-07-24 02:12:49,417 ERROR Unable to locate appender ServerGuiConsole for logger 
[24/7/2016 02:12:49 AM] 2016-07-24 02:12:49,417 ERROR Unable to locate appender ServerGuiConsole for logger net.minecraft
[24/7/2016 02:12:49 AM] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[24/7/2016 02:12:49 AM] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[24/7/2016 02:12:49 AM] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[24/7/2016 02:12:49 AM] [main/INFO] [FML]: Forge Mod Loader version 7.99.39.1566 for Minecraft 1.7.10 loading
[24/7/2016 02:12:49 AM] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_101, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_101
[24/7/2016 02:12:49 AM] [main/INFO] [FML]: [AppEng] Core Init
[24/7/2016 02:12:49 AM] 2016-07-24 02:12:49,551 ERROR Error processing element Queue: CLASS_NOT_FOUND
[24/7/2016 02:12:49 AM] 2016-07-24 02:12:49,560 ERROR Unable to locate appender ServerGuiConsole for logger com.mojang
[24/7/2016 02:12:49 AM] 2016-07-24 02:12:49,561 ERROR Unable to locate appender ServerGuiConsole for logger 
[24/7/2016 02:12:49 AM] 2016-07-24 02:12:49,561 ERROR Unable to locate appender ServerGuiConsole for logger net.minecraft
[24/7/2016 02:12:49 AM] [main/WARN] [FML]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[24/7/2016 02:12:49 AM] [main/WARN] [FML]: The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[24/7/2016 02:12:49 AM] [main/INFO] [FML]: Loading tweaker forestry.shade.javacheck.Java7Checker from forestry_1.7.10-4.2.13.61.jar
[24/7/2016 02:12:49 AM] [main/WARN] [FML]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[24/7/2016 02:12:50 AM] [main/WARN] [FML]: The coremod mrtjp.relocation.asm.RelocationPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[24/7/2016 02:12:50 AM] [main/WARN] [FML]: The coremod ic2.core.coremod.IC2core does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[24/7/2016 02:12:50 AM] [main/WARN] [FML]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[24/7/2016 02:12:50 AM] [main/WARN] [FML]: The coremod logisticspipes.asm.LogisticsPipesCoreLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[24/7/2016 02:12:50 AM] [main/WARN] [FML]: The coremod net.malisis.core.asm.MalisisCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[24/7/2016 02:12:50 AM] [main/WARN] [FML]: The coremod mekanism.common.asm.LoadingHook does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[24/7/2016 02:12:50 AM] [main/WARN] [FML]: The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[24/7/2016 02:12:50 AM] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.DepLoader$DepLoadInst:<init>:333]: MicdoodleCore searching for dependencies in mods file: **USERSDIR**\Instances\BevosTechPack1\mods
[24/7/2016 02:12:50 AM] [main/WARN] [FML]: The coremod mrtjp.core.handler.CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[24/7/2016 02:12:50 AM] [main/WARN] [FML]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[24/7/2016 02:12:50 AM] [main/WARN] [FML]: The coremod openblocks.OpenBlocksCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[24/7/2016 02:12:50 AM] [main/WARN] [FML]: The coremod openmods.core.OpenModsCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[24/7/2016 02:12:50 AM] [main/WARN] [FML]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[24/7/2016 02:12:50 AM] [main/WARN] [FML]: The coremod lumien.randomthings.Transformer.RTLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[24/7/2016 02:12:50 AM] [main/WARN] [FML]: The coremod thaumcraft.codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[24/7/2016 02:12:50 AM] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[24/7/2016 02:12:50 AM] [main/INFO] [LaunchWrapper]: Loading tweak class name forestry.shade.javacheck.Java7Checker
[24/7/2016 02:12:50 AM] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[24/7/2016 02:12:50 AM] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[24/7/2016 02:12:50 AM] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[24/7/2016 02:12:50 AM] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[24/7/2016 02:12:51 AM] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[24/7/2016 02:12:51 AM] [main/ERROR] [FML]: A critical error occurred trying to read the minecraft jar file
[24/7/2016 02:12:51 AM] java.io.FileNotFoundException: D:\Launcher \Instances\BevosTechPack1\bin\minecraft.jar (Das System kann den angegebenen Pfad nicht finden)
[24/7/2016 02:12:51 AM] 	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_101]
[24/7/2016 02:12:51 AM] 	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_101]
[24/7/2016 02:12:51 AM] 	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_101]
[24/7/2016 02:12:51 AM] 	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_101]
[24/7/2016 02:12:51 AM] 	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_101]
[24/7/2016 02:12:51 AM] 	at cpw.mods.fml.common.asm.FMLSanityChecker.call(FMLSanityChecker.java:106) [FMLSanityChecker.class:?]
[24/7/2016 02:12:51 AM] 	at cpw.mods.fml.common.asm.FMLSanityChecker.call(FMLSanityChecker.java:39) [FMLSanityChecker.class:?]
[24/7/2016 02:12:51 AM] 	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:133) [forge-1.7.10-10.13.4.1566-1.7.10-universal.jar:?]
[24/7/2016 02:12:51 AM] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
[24/7/2016 02:12:51 AM] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[24/7/2016 02:12:51 AM] [main/ERROR] [FML]: The minecraft jar file:/D:/Launcher+/Instances/BevosTechPack1/bin/minecraft.jar!/net/minecraft/client/ClientBrandRetriever.class appears to be corrupt! There has been CRITICAL TAMPERING WITH MINECRAFT, it is highly unlikely minecraft will work! STOP NOW, get a clean copy and try again!
[24/7/2016 02:12:51 AM] [main/ERROR] [FML]: For your safety, FML will not launch minecraft. You will need to fetch a clean version of the minecraft jar file
[24/7/2016 02:12:51 AM] [main/ERROR] [FML]: Technical information: The class net.minecraft.client.ClientBrandRetriever should have been associated with the minecraft jar file, and should have returned us a valid, intact minecraft jar location. This did not work. Either you have modified the minecraft jar file (if so run the forge installer again), or you are using a base editing jar that is changing this class (and likely others too). If you REALLY want to run minecraft in this configuration, add the flag -Dfml.ignoreInvalidMinecraftCertificates=true to the 'JVM settings' in your launcher profile.
[24/7/2016 02:12:51 AM] Exception in thread "main" [02:12:51] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.ExceptionInInitializerError
[24/7/2016 02:12:51 AM] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.asm.FMLSanityChecker.call(FMLSanityChecker.java:159)
[24/7/2016 02:12:51 AM] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.asm.FMLSanityChecker.call(FMLSanityChecker.java:39)
[24/7/2016 02:12:51 AM] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:133)
[24/7/2016 02:12:51 AM] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[24/7/2016 02:12:51 AM] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[24/7/2016 02:12:51 AM] [02:12:51] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NullPointerException
[24/7/2016 02:12:51 AM] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.Loader.<init>(Loader.java:198)
[24/7/2016 02:12:51 AM] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.Loader.instance(Loader.java:176)
[24/7/2016 02:12:51 AM] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.FMLCommonHandler.<init>(FMLCommonHandler.java:87)
[24/7/2016 02:12:51 AM] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.FMLCommonHandler.<clinit>(FMLCommonHandler.java:77)
[24/7/2016 02:12:51 AM] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 5 more
[24/7/2016 02:12:51 AM] Checking for updated files!
[24/7/2016 02:12:51 AM] No updates found!
[24/7/2016 02:12:57 AM] Copied Log to clipboard

**Comment by b0bst3r** [comment]
Read the log and follow the instructions:

The minecraft jar file:/D:/Launcher+/Instances/BevosTechPack1/bin/minecraft.jar!/net/minecraft/client/ClientBrandRetriever.class appears to be corrupt! There has been CRITICAL TAMPERING WITH MINECRAFT, it is highly unlikely minecraft will work! STOP NOW, get a clean copy and try again!

For your safety, FML will not launch minecraft. You will need to fetch a clean version of the minecraft jar file
