### ISSUE TITLE
Crash on game load

### ISSUE THREAD

**Issue by asiantator** [BevoTechPack/BevoTechPack#1124]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 

### Description of issue/bug

Crash on Instance start. Have uninstalled, restarted, reinstalled, restarted multiple times to no effect.

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

Log: http://pastebin.com/tAuydr18
Crash Report: http://pastebin.com/dSU5F09b

Questions:

Did you add any additional mods? - No
Do you use optifine? -No
Did the problem appear in single player or on a server? - Single

**Comment by Watschman** [comment]
Error is caused by factorization, removing that mod should at least start minecraft.
I'm not sure why it crashed though looks like the verification of this mod failed to load.

**Comment by asiantator** [comment]
Problem is sorted.

Issue was an update to avast screwed up the exceptions list. It wasn't allowing JAVA thru the firewall. Uninstalled then reinstalled Avast and it sorted itself out.

Did a bit of checking on this line of code which is what lead to Avast being the culprit

Caused by: java.io.IOException: Unable to establish loopback connection
    at sun.nio.ch.PipeImpl$Initializer.run(Unknown Source)
    at sun.nio.ch.PipeImpl$Initializer.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.nio.ch.PipeImpl.<init>(Unknown Source)
    at sun.nio.ch.SelectorProviderImpl.openPipe(Unknown Source)
    at java.nio.channels.Pipe.open(Unknown Source)
    at sun.nio.ch.WindowsSelectorImpl.<init>(Unknown Source)
    at sun.nio.ch.WindowsSelectorProvider.openSelector(Unknown Source)
    at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:126)

Thanks gents you can close this
