### ISSUE TITLE
No Idea?

### ISSUE THREAD

**Issue by JulesDaKitty** [BevoTechPack/BevoTechPack#1172]
Failure to give adequate information on issues/bugs will be subject to immediate possible closure/spankings.

Bevo Tech Pack Version :- 
Latest
### Description of issue/bug
Crashing upon entering server since I switched to creative
java.io.IOexception: an existing connection was forcibly closed by the remote host 
^is what is says on cmd and then I instantly get a crashed game
### Steps to reproduce the issue/bug
Tried playing singleplayer but nothing happened.

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)
https://pastebin.com/4cnQ3ARh
Questions:

Did you add any additional mods? - 
Yes: Equivalent Exchange 3
Do you use optifine? -
No
Did the problem appear in single player or on a server? - 
Server that I have.

**Comment by JulesDaKitty** [comment]
I would post the other fml-client-latest but its so log it won't go on paste bin

**Comment by JulesDaKitty** [comment]
Loading Player: JulesDaKitty
[01:09:33] [Server thread/DEBUG] [NotEnoughItems/]: Sending serverside check to: JulesDaKitty
[01:09:33] [Server thread/INFO] [Waila/]: Player EntityPlayerMP['JulesDaKitty'/3007, l='world', x=104.85, y=68.00, z=-8.93] connected. Sending ping
[01:09:33] [ForkJoinPool-1-worker-3/INFO] [OpenComputers/]: Starting OpenComputers version check.
[01:09:33] [Server thread/INFO] [Mekanism/]: Sent config to 'JulesDaKitty.'
[01:09:33] [Server thread/INFO] [mcjty.lib.varia.Logging/]: SMP: Player logged in: Sync diminfo to clients
[01:09:33] [Server thread/INFO] [mcjty.lib.varia.Logging/]: Sync dimension info to clients!
[01:09:33] [Server thread/INFO] [mcjty.lib.varia.Logging/]: Send validation data to the client
[01:09:34] [ForkJoinPool-1-worker-3/INFO] [OpenComputers/]: A newer version of OpenComputers is available: v1.7.0.
[01:09:39] [Server thread/INFO] [STDOUT/]: [mcjty.lib.preferences.PreferencesProperties:syncToClient:38]: syncToClient: style = STYLE_FLAT_GRADIENT
[01:09:48] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save world
[01:10:16] [Netty IO #2/ERROR] [FML/]: NetworkDispatcher exception
java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_112]
	at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_112]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_112]
	at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_112]
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_112]
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:436) ~[UnpooledUnsafeDirectByteBuf.class:?]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:870) ~[AbstractByteBuf.class:?]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:208) ~[NioSocketChannel.class:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:87) [AbstractNioByteChannel$NioByteUnsafe.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) [NioEventLoop.class:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_112]
[01:10:16] [Server thread/DEBUG] [NotEnoughItems/]: Unloading Player: JulesDaKitty
[01:10:17] [Netty IO #3/TRACE] [FML/]: $ClientHello->FMLHandshakeServerState$2:HELLO 
What I got from the server logs

**Comment by GavyLavy** [comment]
I happen to be on the same server as Jules and haven’t experienced any problems like this.
