### ISSUE TITLE
-Minecraft Crash Report-  ~~ERROR~~  No OpenGL context found in the current thread

### ISSUE THREAD

**Issue by TropicSenpai** [BevoTechPack/BevoTechPack#1194]
Hey there I am trying to run RLCraft the new Minecraft mod via Twitch but everytime I am in a Single Player World it crashes and says: 
The game crashed whilst exception in server tick loop
Error: java.lang.RuntimeException: Ruins mod crashed because it was denied file write access to C:\Users\Marius\Twitch\Minecraft\Instances\RLCraft\saves\New World\BattletowerPositionsFile.txt

The freeze/crash occurs in less than 10 minutes into the game. 
I tried solving this kind of error but couldn´t find much help.

Things I Tried:
-Java update
-Delete and reinstall Java 
-Delete and downgrade Java to Java version 8 update 51 (68 bit)
-Delete the modpack / minecraft file reinstall it 
-Update anykind of triber i have ( Intel® HD Graphics 4600/ NVIDIA GeForce GTX 970/ Intel® 
 Core™ i7-4790K CPU @ 4.00GHz)

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LibLoader (# LibLoader.jar)
  RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  CreativePatchingLoader (CreativeCore_v1.9.45_mc1.12.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  CorePlugin (ForgeEndertech-1.12.2-4.4.20.0-build.0354.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  LoadingPlugin (Reskillable-1.12.2-1.12.5.jar)
  MMFMLCorePlugin (MultiMine-1.12.2.jar)
  CoreMod (TickProfiler-1.12-0.0.7.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.16-universal.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  ItemPatchingLoader (ItemPhysic_Full_1.4.21_mc1.12.2.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  TNTUtilities Core (tnt_utilities-mc1.12-1.2.3.jar)
  LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 9/20/19 6:50 PM
Description: Exception in server tick loop

java.lang.RuntimeException: Ruins mod crashed because it was denied file write access to C:\Users\Marius\Twitch\Minecraft\Instances\RLCraft\saves\New World\BattletowerPositionsFile.txt
	at atomicstryker.battletowers.common.WorldGenHandler.flushCurrentPosListToFile(WorldGenHandler.java:379)
	at atomicstryker.battletowers.common.WorldGenHandler.eventWorldSave(WorldGenHandler.java:63)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_884_WorldGenHandler_eventWorldSave_Save.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1008)
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:408)
	at net.minecraft.server.integrated.IntegratedServer.func_71267_a(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:691)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 869984624 bytes (829 MB) / 2380267520 bytes (2270 MB) up to 3008888832 bytes (2869 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3228m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2803 126 mods loaded, 126 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                          | Version              | Source                                         | Signature                                |
	|:------ |:--------------------------- |:-------------------- |:---------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                   | 1.12.2               | minecraft.jar                                  | None                                     |
	| LCHIJA | mcp                         | 9.42                 | minecraft.jar                                  | None                                     |
	| LCHIJA | FML                         | 8.0.99.99            | forge-1.12.2-14.23.5.2803.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                       | 14.23.5.2803         | forge-1.12.2-14.23.5.2803.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | creativecoredummy           | 1.0.0                | minecraft.jar                                  | None                                     |
	| LCHIJA | itemphysic                  | 1.4.0                | minecraft.jar                                  | None                                     |
	| LCHIJA | ivtoolkit                   | 1.3.3-1.12           | minecraft.jar                                  | None                                     |
	| LCHIJA | foamfixcore                 | 7.7.4                | minecraft.jar                                  | None                                     |
	| LCHIJA | tnt_utilities_core          | 1.2.3                | minecraft.jar                                  | None                                     |
	| LCHIJA | dsurroundcore               | 3.5.4.3              | minecraft.jar                                  | None                                     |
	| LCHIJA | forgeendertech              | 1.12.2-4.4.20.0      | ForgeEndertech-1.12.2-4.4.20.0-build.0354.jar  | None                                     |
	| LCHIJA | adhooks                     | 1.12.2-3.2.2.0       | AdHooks-1.12.2-3.2.2.0-build.0220.jar          | None                                     |
	| LCHIJA | advanced-fishing            | 1.3.3                | Advanced-Fishing-1.12.2-1.3.3.jar              | None                                     |
	| LCHIJA | alcatrazcore                | 1.0.4                | alcatrazcore-1.0.4.jar                         | 3c2d6be715971d1ed58a028cdb3fae72987fc934 |
	| LCHIJA | antiqueatlas                | 4.5.1                | antiqueatlas-1.12.2-4.5.1.jar                  | e631d7254e451d0360d0148cb21407d5511d45e9 |
	| LCHIJA | antiqueatlasoverlay         | 1.2                  | antiqueatlas-1.12.2-4.5.1.jar                  | e631d7254e451d0360d0148cb21407d5511d45e9 |
	| LCHIJA | anvilpatch                  | 1.0.0                | anvilpatch-1.0.0.jar                           | None                                     |
	| LCHIJA | aquaculture                 | 1.6.8                | Aquaculture-1.12.2-1.6.8.jar                   | None                                     |
	| LCHIJA | carrots                     | 1.0.0b1              | carrotslib-mc1.12.2-1.0.0b1.jar                | None                                     |
	| LCHIJA | armorunder                  | 1.0.0                | armorunder-mc1.12.2-1.0.0.jar                  | None                                     |
	| LCHIJA | artemislib                  | 1.0.4                | ArtemisLib-1.12.2-v1.0.4.jar                   | None                                     |
	| LCHIJA | autoreglib                  | 1.3-30               | AutoRegLib-1.3-30.jar                          | None                                     |
	| LCHIJA | battletowers                | 1.6.4                | BattleTowers-1.12.2.jar                        | None                                     |
	| LCHIJA | baubles                     | 1.5.2                | Baubles-1.12-1.5.2.jar                         | None                                     |
	| LCHIJA | baubleshud                  | 5.0.2                | BaublesHud-1.12.2-5.0.2.jar                    | None                                     |
	| LCHIJA | mujmajnkraftsbettersurvival | 1.3.4                | Better_Survival-1.3.4(1.12.1).jar              | None                                     |
	| LCHIJA | bettercombatmod             | 1.5.6                | BetterCombat-1.12.2-1.5.6.jar                  | None                                     |
	| LCHIJA | forgelin                    | 1.8.2                | Forgelin-1.8.2.jar                             | None                                     |
	| LCHIJA | betterfoliage               | 2.2.0                | BetterFoliage-MC1.12-2.2.0.jar                 | None                                     |
	| LCHIJA | bloodmoon                   | 1.5.3                | Bloodmoon-MC1.12.2-1.5.3.jar                   | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | cursedlib                   | 1.0.0                | FlameLib-1.12.2-0.0.7.jar                      | None                                     |
	| LCHIJA | bountifulbaubles            | 0.0.1                | Bountiful Baubles-1.12.2-0.0.6.jar             | None                                     |
	| LCHIJA | campfire                    | 1.2                  | campfire-1.12-v1.2.jar                         | None                                     |
	| LCHIJA | carryon                     | 1.12.1               | CarryOn MC1.12.2 v1.12.1.jar                   | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| LCHIJA | chunkanimator               | 1.2                  | ChunkAnimator-MC1.12-1.2.jar                   | None                                     |
	| LCHIJA | toughasnails                | 3.1.0.141            | ToughAsNails-1.12.2-3.1.0.141-universal.jar    | None                                     |
	| LCHIJA | comforts                    | 1.4.1.2              | comforts-1.12.2-1.4.1.2.jar                    | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | reskillable                 | 1.12.2-GRADLE:BUILD  | Reskillable-1.12.2-1.12.5.jar                  | None                                     |
	| LCHIJA | compatskills                | 1.12.2-1.15.0        | CompatSkills-1.12.2-1.15.0.jar                 | None                                     |
	| LCHIJA | coralreef                   | 2.0                  | CoralReef-2.5-1.12.2.jar                       | None                                     |
	| LCHIJA | wearablebackpacks           | 3.1.3                | WearableBackpacks-1.12.2-3.1.3.jar             | None                                     |
	| LCHIJA | corpsecomplex               | 1.0.5.1              | corpsecomplex-1.12.2-1.0.5.1.jar               | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | craftablechainmail          | 1.0                  | craftablechainmail-1.0.jar                     | None                                     |
	| LCHIJA | craftablehorsearmour        | 1.3                  | CraftableHorseArmour-1.3.0-1.12.jar            | None                                     |
	| LCHIJA | crafttweaker                | 4.1.18               | CraftTweaker2-1.12-4.1.18.jar                  | None                                     |
	| LCHIJA | ctgui                       | 1.0.0                | CraftTweaker2-1.12-4.1.18.jar                  | None                                     |
	| LCHIJA | jei                         | 4.15.0.268           | jei_1.12.2-4.15.0.268.jar                      | None                                     |
	| LCHIJA | crafttweakerjei             | 2.0.3                | CraftTweaker2-1.12-4.1.18.jar                  | None                                     |
	| LCHIJA | creativecore                | 1.9.9                | CreativeCore_v1.9.45_mc1.12.2.jar              | None                                     |
	| LCHIJA | defiledlands                | 1.4.2                | defiledlands-1.12.2-1.4.2.jar                  | None                                     |
	| LCHIJA | disenchanter                | 1.6                  | disenchanter-[1.12]1.6.jar                     | None                                     |
	| LCHIJA | dldungeonsjbg               | 1.12.5               | DoomlikeDungeons-1.12.5-MC1.12.2.jar           | None                                     |
	| LCHIJA | dynamictrees                | 1.12.2-0.9.5         | DynamicTrees-1.12.2-0.9.5.jar                  | None                                     |
	| LCHIJA | traverse                    | 1.6.0                | Traverse-1.12.2-1.6.0-69.jar                   | None                                     |
	| LCHIJA | dttraverse                  | 1.5                  | dttraverse-1.5.jar                             | None                                     |
	| LCHIJA | enhancedvisuals             | 1.0                  | EnhancedVisuals_v1.2.1_mc1.12.2.jar            | None                                     |
	| LCHIJA | familiarfauna               | 1.0.11               | FamiliarFauna-1.12.2-1.0.11.jar                | None                                     |
	| LCHIJA | fbp                         | 2.4.1                | FancyBlockParticles-1.12.x-2.4.1.jar           | None                                     |
	| LCHIJA | firstaid                    | 1.6.7                | firstaid-1.6.7.jar                             | 7904c4e13947c8a616c5f39b26bdeba796500722 |
	| LCHIJA | foamfix                     | 0.10.5-1.12.2        | foamfix-0.10.5-1.12.2.jar                      | None                                     |
	| LCHIJA | foodexpansion               | 1.3                  | FoodExpansion1.3.3-1.12.2.jar                  | None                                     |
	| LCHIJA | tschipplib                  | 1.1                  | TschippLib MC1.12 v1.1.jar                     | None                                     |
	| LCHIJA | forgottenitems              | 1.1                  | ForgottenItems MC1.12.2 v1.1.jar               | None                                     |
	| LCHIJA | globalgamerules             | 2.2                  | GlobalGameRules-1.12.2-2.2.7.jar               | None                                     |
	| LCHIJA | grapplemod                  | 1.12.2-v11.1         | grapplemod-v11.1-1.12.2.jar                    | None                                     |
	| LCHIJA | llibrary                    | 1.7.19               | llibrary-1.7.19-1.12.2.jar                     | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire                  | 1.7.1                | iceandfire-1.7.1-1.12.2.jar                    | None                                     |
	| LCHIJA | infernalmobs                | 1.7.6                | InfernalMobs-1.12.1.jar                        | None                                     |
	| LCHIJA | inventorytweaks             | 1.64+dev.146.2180b27 | InventoryTweaks-1.64+dev.146.jar               | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | levelup2                    | ${version}           | Level Up! 2-1.1.22-1.12.jar                    | None                                     |
	| LCHIJA | loottweaker                 | 0.0.9                | LootTweaker-1.12.2-0.0.9.jar                   | None                                     |
	| LCHIJA | lostcities                  | 2.0.20               | lostcities-1.12-2.0.20.jar                     | None                                     |
	| LCHIJA | lostsouls                   | 1.1.4                | lostsouls-1.12-1.1.4.jar                       | None                                     |
	| LCHIJA | lycanitesmobs               | 1.21.0.0 - MC 1.12.2 | lycanitesmobs-1.12.2-1.21.0.0.jar              | None                                     |
	| LCHIJA | arcticmobs                  | 1.21.0.0 - MC 1.12.2 | lycanitesmobs-1.12.2-1.21.0.0.jar              | None                                     |
	| LCHIJA | demonmobs                   | 1.21.0.0 - MC 1.12.2 | lycanitesmobs-1.12.2-1.21.0.0.jar              | None                                     |
	| LCHIJA | desertmobs                  | 1.21.0.0 - MC 1.12.2 | lycanitesmobs-1.12.2-1.21.0.0.jar              | None                                     |
	| LCHIJA | elementalmobs               | 1.21.0.0 - MC 1.12.2 | lycanitesmobs-1.12.2-1.21.0.0.jar              | None                                     |
	| LCHIJA | forestmobs                  | 1.21.0.0 - MC 1.12.2 | lycanitesmobs-1.12.2-1.21.0.0.jar              | None                                     |
	| LCHIJA | freshwatermobs              | 1.21.0.0 - MC 1.12.2 | lycanitesmobs-1.12.2-1.21.0.0.jar              | None                                     |
	| LCHIJA | infernomobs                 | 1.21.0.0 - MC 1.12.2 | lycanitesmobs-1.12.2-1.21.0.0.jar              | None                                     |
	| LCHIJA | junglemobs                  | 1.21.0.0 - MC 1.12.2 | lycanitesmobs-1.12.2-1.21.0.0.jar              | None                                     |
	| LCHIJA | mountainmobs                | 1.21.0.0 - MC 1.12.2 | lycanitesmobs-1.12.2-1.21.0.0.jar              | None                                     |
	| LCHIJA | plainsmobs                  | 1.21.0.0 - MC 1.12.2 | lycanitesmobs-1.12.2-1.21.0.0.jar              | None                                     |
	| LCHIJA | saltwatermobs               | 1.21.0.0 - MC 1.12.2 | lycanitesmobs-1.12.2-1.21.0.0.jar              | None                                     |
	| LCHIJA | shadowmobs                  | 1.21.0.0 - MC 1.12.2 | lycanitesmobs-1.12.2-1.21.0.0.jar              | None                                     |
	| LCHIJA | swampmobs                   | 1.21.0.0 - MC 1.12.2 | lycanitesmobs-1.12.2-1.21.0.0.jar              | None                                     |
	| LCHIJA | mobends                     | 0.24                 | mobends-0.24_for_MC-1.12.jar                   | None                                     |
	| LCHIJA | multimine                   | 1.6.0                | MultiMine-1.12.2.jar                           | None                                     |
	| LCHIJA | neat                        | 1.4-17               | Neat 1.4-17.jar                                | None                                     |
	| LCHIJA | notreepunching              | 2.0.13               | notreepunching-2.0.13.jar                      | 3c2d6be715971d1ed58a028cdb3fae72987fc934 |
	| LCHIJA | potioncore                  | 1.6_for_1.12.2       | PotionCore-1.6_for_1.12.2.jar                  | None                                     |
	| LCHIJA | potionfingers               | r1.0-2               | PotionFingers-r1.0-2.jar                       | None                                     |
	| LCHIJA | qualitytools                | 1.0.6_for_1.12.2     | QualityTools-1.0.6_for_1.12.2.jar              | None                                     |
	| LCHIJA | realistictorches            | 2.1.1                | RealisticTorches-1.12.2-2.1.1.jar              | None                                     |
	| LCHIJA | reccomplex                  | 1.4.8.2              | RecurrentComplex-1.4.8.2.jar                   | None                                     |
	| LCHIJA | roguelike                   | 1.8.0                | RoguelikeDungeons-1.12.2-1.8.0.jar             | None                                     |
	| LCHIJA | roughtweaks                 | 1.0                  | roughTweaks0.2.4-1.12.2.jar                    | None                                     |
	| LCHIJA | ruins                       | 17.1                 | Ruins-1.12.2.jar                               | None                                     |
	| LCHIJA | silentlib                   | 3.0.13               | SilentLib-1.12.2-3.0.13+167.jar                | None                                     |
	| LCHIJA | scalinghealth               | 1.3.36               | ScalingHealth-1.12.2-1.3.36+140.jar            | None                                     |
	| LCHIJA | sereneseasons               | 1.2.16               | SereneSeasons-1.12.2-1.2.16-universal.jar      | None                                     |
	| LCHIJA | sit                         | v1.1.2               | sit-1.12.x-v1.1.2.jar                          | None                                     |
	| LCHIJA | somanyenchantments          | 0.4.3                | somanyenchantments V0.4.3.jar                  | None                                     |
	| LCHIJA | soundfilters                | 0.10_for_1.12        | SoundFilters-0.10_for_1.12.jar                 | None                                     |
	| LCHIJA | spartanweaponry             | beta 1.2.3           | SpartanWeaponry-1.12.2-beta-1.2.3.jar          | None                                     |
	| LCHIJA | spartanfire                 | 0.05                 | spartanfire-0.05.jar                           | None                                     |
	| LCHIJA | spartanshields              | 1.5.4                | SpartanShields-1.12.2-1.5.4.jar                | None                                     |
	| LCHIJA | spawnercontrol              | 1.6.2                | SpawnerControl-1.6.2.jar                       | None                                     |
	| LCHIJA | stg                         | 1.12.2-1.2.3         | stg-1.12.2-1.2.3.jar                           | None                                     |
	| LCHIJA | switchbow                   | 1.5.6                | switchbow-1.5.6.jar                            | None                                     |
	| LCHIJA | tanspit                     | 1.12.2-1.3           | tanspit-1.12.2-1.3.jar                         | None                                     |
	| LCHIJA | tickprofiler                | 1.12-0.0.7           | TickProfiler-1.12-0.0.7.jar                    | None                                     |
	| LCHIJA | tnt_utilities               | 1.2.3                | tnt_utilities-mc1.12-1.2.3.jar                 | None                                     |
	| LCHIJA | toolbelt                    | 1.7.1                | ToolBelt-1.12.0-1.7.1.jar                      | None                                     |
	| LCHIJA | xat                         | 0.25.1               | Trinkets and Baubles-1.12.2-0.25.1.jar         | None                                     |
	| LCHIJA | trumpetskeleton             | 1.12-1.0.2.1         | trumpetskeleton-1.12-1.0.2.1.jar               | None                                     |
	| LCHIJA | tumbleweed                  | 1.11-0.4.5           | tumbleweed-1.11-0.4.5.jar                      | None                                     |
	| LCHIJA | variedcommodities           | 1.12.2               | VariedCommodities_1.12.2(15may18.jar           | None                                     |
	| LCHIJA | waystones                   | 4.0.67               | Waystones_1.12.2-4.0.67.jar                    | None                                     |
	| LCHIJA | wolfarmor                   | 2.2.3.6              | wolfarmor-1.12.2-2.2.3.1798-universal.jar      | None                                     |
	| LCHIJA | xpbook                      | 0.0.3-beta           | xpbook-1.12-0.0.3-beta.jar                     | None                                     |
	| LCHIJA | xpfromharvest               | 1.1.0                | xpfromharvest-1.12.2-1.1.0.jar                 | None                                     |
	| LCHIJA | orelib                      | 3.5.2.2              | OreLib-1.12.2-3.5.2.2.jar                      | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dsurround                   | 3.5.4.3              | DynamicSurroundings-1.12.2-3.5.4.3.jar         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dshuds                      | 3.5.4.0              | DynamicSurroundingsHuds-1.12.2-3.5.4.0BETA.jar | 7a2128d395ad96ceb9d9030fbd41d035b435753a |

	Loaded coremods (and transformers): 
LibLoader (# LibLoader.jar)
  
RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
  pw.prok.realbench.asm.RBTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
CreativePatchingLoader (CreativeCore_v1.9.45_mc1.12.2.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  invtweaks.forge.asm.ContainerTransformer
CorePlugin (ForgeEndertech-1.12.2-4.4.20.0-build.0354.jar)
  
ForgelinPlugin (Forgelin-1.8.2.jar)
  
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
LoadingPlugin (Reskillable-1.12.2-1.12.5.jar)
  codersafterdark.reskillable.base.asm.ClassTransformer
MMFMLCorePlugin (MultiMine-1.12.2.jar)
  atomicstryker.multimine.common.fmlmagic.MMTransformer
CoreMod (TickProfiler-1.12-0.0.7.jar)
  
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.16-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
ItemPatchingLoader (ItemPhysic_Full_1.4.21_mc1.12.2.jar)
  com.creativemd.itemphysic.ItemTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  org.orecruncher.dsurround.asm.Transformer
TNTUtilities Core (tnt_utilities-mc1.12-1.2.3.jar)
  ljfa.tntutils.asm.ExplosionTransformer
LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Tropic_Player99'/147, l='New World', x=970.19, y=97.00, z=-4868.96]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
 

### Link to crashlog (do not paste full crash logs in this issue, use pastebin.com)

Questions:

Did you add any additional mods? - 
Do you use optifine? -
Did the problem appear in single player or on a server? -

**Comment by TropicSenpai** [comment]
This Problem occurs with and without optifine in every single player game
