### ISSUE TITLE
[BTP11Full] Server Console Spam and Server Tick Spikes

### ISSUE THREAD

**Issue by FatherOwnage** [BevoTechPack/BevoTechPack#769]
The following messages below keep hitting my console about every 2 minutes. The tps spike up a bit when it happens too.

[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.util.ConcurrentModificationException
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:370)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.util.LinkedHashMap$KeyIterator.next(LinkedHashMap.java:381)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at mekanism.api.transmitters.DynamicNetwork.fullRefresh(DynamicNetwork.java:95)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at mekanism.common.multipart.PartTransmitter.getTransmitterNetwork(PartTransmitter.java:122)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at mekanism.common.multipart.PartTransmitter.getTransmitterNetwork(PartTransmitter.java:86)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at mekanism.common.multipart.PartTransmitter.refreshTransmitterNetwork(PartTransmitter.java:43)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at TGridTransmitter$$16$class.refreshTransmitterNetwork(Unknown Source)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at TileMultipart_cmp$$34.refreshTransmitterNetwork(Unknown Source)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at mekanism.api.transmitters.TransmitterNetworkRegistry$NetworkLoader.refreshChunk(TransmitterNetworkRegistry.java:150)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at mekanism.api.transmitters.TransmitterNetworkRegistry$NetworkLoader.onChunkLoad(TransmitterNetworkRegistry.java:132)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.common.eventhandler.ASMEventHandler_638_NetworkLoader_onChunkLoad_Load.invoke(.dynamic)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:923)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:46)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.world.World.func_72964_e(World.java:419)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.world.World.func_147439_a(World.java:345)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.world.World.func_72878_l(World.java:3422)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.world.World.func_72864_z(World.java:3428)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at mekanism.common.multipart.PartSidedPipe.getPossibleTransmitterConnections(PartSidedPipe.java:176)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at mekanism.common.multipart.PartTransmitter.getTransmitterNetwork(PartTransmitter.java:94)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at mekanism.common.multipart.PartTransmitter.getTransmitterNetwork(PartTransmitter.java:86)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at mekanism.common.multipart.PartTransmitter.refreshTransmitterNetwork(PartTransmitter.java:43)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at TGridTransmitter$$16$class.refreshTransmitterNetwork(Unknown Source)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at TileMultipart_cmp$$34.refreshTransmitterNetwork(Unknown Source)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at mekanism.api.transmitters.TransmitterNetworkRegistry$NetworkLoader.refreshChunk(TransmitterNetworkRegistry.java:150)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at mekanism.api.transmitters.TransmitterNetworkRegistry$NetworkLoader.onChunkLoad(TransmitterNetworkRegistry.java:132)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.common.eventhandler.ASMEventHandler_638_NetworkLoader_onChunkLoad_Load.invoke(.dynamic)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:923)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:46)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.world.World.func_72964_e(World.java:419)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.world.World.func_147439_a(World.java:345)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at mods.natura.blocks.trees.NLeaves.func_149674_a(NLeaves.java:93)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:391)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:183)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[18:29:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by FiveEYZ** [comment]
just wanna say that im getting the same error spam.
here is a log of the error http://pastebin.com/xf84k4kM

**Comment by BevoLJ** [comment]
Just updated the pack. Please let me know if this is still an issue in BTP 12.
