### ISSUE TITLE
Unexpected Exception: Progressive Automation Planter

### ISSUE THREAD

**Issue by robbcrg** [BevoTechPack/BevoTechPack#817]
Just in case anyone else spots this. Seems to happen when the hoe runs low ... This is new for Bevo 12. I reported it to the mod author as well. I do not have a workaround (except switch to MFR which is a bit more complexity than I feel the need for my little base).

[14:49:47] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.jav
a:642) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(Dedicated
Server.java:334) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.jav
a:547) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [M
inecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[li.class:?]
Caused by: java.lang.NullPointerException
        at com.vanhal.progressiveautomation.ref.ToolHelper.damageTool(ToolHelper
.java:161) ~[ToolHelper.class:?]
        at com.vanhal.progressiveautomation.entities.planter.TilePlanter.damageH
oe(TilePlanter.java:225) ~[TilePlanter.class:?]
        at com.vanhal.progressiveautomation.entities.planter.TilePlanter.harvest
Plant(TilePlanter.java:145) ~[TilePlanter.class:?]
        at com.vanhal.progressiveautomation.entities.planter.TilePlanter.func_14
5845_h(TilePlanter.java:69) ~[TilePlanter.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?
]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[
mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.jav
a:636) ~[MinecraftServer.class:?]
        ... 4 more

**Comment by BevoLJ** [comment]
He fixed that crash here: https://github.com/Vanhal/ProgressiveAutomation/commit/b8aa268d0cef4e231a3cbea49340e3d2e2f47e07

This will be in an update this week.

**Comment by BevoLJ** [comment]
You need you can grab his latest version for a fix until I can push out an update to the pack.

**Comment by robbcrg** [comment]
Thanks,

I will just wait. I have PLENTY of resources and can turn off the 
planters for now. That way when you have a fix I can test it in the 
exact same state it failed in.

Thank you.

(I could not find out how to reply to a closed ticket).

**Comment by BevoLJ** [comment]
Right on.  Will likely be out late in the week/weekend.  There are a few other things I'd like to throw in that I am waiting on as well.  :)

**Comment by robbcrg** [comment]
When it comes to mods and mod-packs, patience and flexibility is key. 
You and your fellows that make these assets are under appreciated.

Thank you!
