### ISSUE TITLE
Placing an un-owned Signalum locked item causes client crash (SMP)

### ISSUE THREAD

**Issue by mSt3in** [BevoTechPack/BevoTechPack#819]
In my case a freshly made tesseract.  Added a Signalum lock, and placed it to make me the owner.  Client crashed.   Tess still got placed, and I'm the owner.  Picking/up replacing owned tess works fine.

(And I see TF has an update ready, already...related?)

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2/23/15 5:42 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.server.management.PreYggdrasilConverter.func_152719_a(SourceFile:244)
	at cofh.thermalexpansion.block.TileInventory.setOwnerName(TileInventory.java:346)
	at cofh.thermalexpansion.block.ender.BlockEnder.func_149689_a(BlockEnder.java:76)
	at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:213)
	at net.minecraft.item.ItemBlock.func_77648_a(ItemBlock.java:103)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:129)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:360)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1435)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1941)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by BevoLJ** [comment]
should be fixed indev
