### ISSUE TITLE
Strange Error and Lagging

### ISSUE THREAD

**Issue by Jibbity** [BevoTechPack/BevoTechPack#864]
I've been having an issue where my server has been lagging significantly and displaying the same error message repeatedly, once a second or so based on a sample of the timestamps. I've included an example below 

>[23:38:22] [Server thread/ERROR]: "Silently" catching entity tracking error.
net.minecraft.util.ReportedException: Adding entity to track
	at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:230) [mn.class:?]
	at cpw.mods.fml.common.registry.EntityRegistry.tryTrackingEntity(EntityRegistry.java:364) [EntityRegistry.class:?]
	at net.minecraft.entity.EntityTracker.func_72786_a(EntityTracker.java:61) [mn.class:?]
	at net.minecraft.world.WorldManager.func_72703_a(SourceFile:31) [mp.class:?]
	at net.minecraft.world.World.func_72923_a(World.java:1347) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72923_a(WorldServer.java:844) [mt.class:?]
	at net.minecraft.world.World.func_72868_a(World.java:3304) [ahb.class:?]
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:921) [apx.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:46) [ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12) [ChunkIOProvider.class:?]
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) [AsynchronousExecutor.class:?]
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) [AsynchronousExecutor.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) [ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) [ahb.class:?]
	at net.minecraft.block.BlockFire.getChanceToEncourageFire(BlockFire.java:516) [alb.class:?]
	at net.minecraft.block.BlockFire.func_149845_m(BlockFire.java:269) [alb.class:?]
	at net.minecraft.block.BlockFire.func_149674_a(BlockFire.java:169) [alb.class:?]
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:550) [mt.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:181) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.IllegalStateException: Entity is already tracked!
	at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:196) ~[mn.class:?]
>	... 27 more

And I can't make heads or tails of it. I can't even really tell what's broken, besides that it looks like java. Any help would be greatly appreciated. If someone tells me how to add the full server logs I'd be happy to do so.

**Comment by b0bst3r** [comment]
Old issue, cleaning up github ready for new release, let me know if this is still a problem.
