### ISSUE TITLE
Game crashes when logging on to server

### ISSUE THREAD

**Issue by jsson98** [BevoTechPack/BevoTechPack#872]
Hello,
I have hosted a server with BTP for about 1 week. Just today my game crashed while playing with a friend. When i trie to reconnect to my server after starting the game it keeps crashing back to desctop  about 5 seconds after i press connnect. My friend says my character appears ingame for about 1 sec and thed dissapears. Just like i logged off. I can play regular singerplayer without any issues. 

I can post the ATlauncher log to but i dont know how, since it is so big. Tips apreachiated

Here is the server logg and the AT launcher logg:
[19:00:57] [Server thread/INFO]: jsson98[/127.0.0.1:52546] logged in with entity
 id 250 at (-182.07887035249155, 178.8215999984741, 203.86282204193992)
[19:00:57] [Server thread/INFO]: jsson98 joined the game
[19:00:57] [Server thread/INFO] [Mekanism]: Sent config to 'jsson98.'
[19:00:57] [Server thread/WARN] [EnhancedPortals]: Unable to get the latest vers
ion information
[19:01:09] [Netty IO #5/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: En befintlig anslutning tvingades att stõnga av fjõrrvõrdda
torn
        at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_31]
        at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_31]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_31]
        at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_31]
        at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_31]
        at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDi
rectByteBuf.java:436) ~[UnpooledUnsafeDirectByteBuf.class:?]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:870)
~[AbstractByteBuf.class:?]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketCha
nnel.java:208) ~[NioSocketChannel.class:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(Abstra
ctNioByteChannel.java:87) [AbstractNioByteChannel$NioByteUnsafe.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.jav
a:480) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEve
ntLoop.java:447) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) [NioEven
tLoop.class:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThread
EventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]
[19:01:09] [Server thread/INFO]: jsson98 lost connection: TranslatableComponent{
key='disconnect.genericReason', args=[Internal Exception: java.io.IOException: E
n befintlig anslutning tvingades att stõnga av fjõrrvõrddatorn], siblings=[], st
yle=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null,
obfuscated=null, clickEvent=null, hoverEvent=null}}
[19:01:09] [Server thread/INFO]: jsson98 left the game

**Comment by MinecraftERP** [comment]
This happens to me as well PLEASE help someone

**Comment by b0bst3r** [comment]
If a friend is stood next to you in game and sees you log in and out then it's something in your inventory that's most likely causing an issue.  It's certainly something which we can eliminate.

On the server locate the world\playerdata folder, in this are several files and a dat file for every player which is the UUid number of the player.  Use a website like http://mcuuid.net/ to lookup your playername and get the UUID number.  Rename the relevant file or move it out of the way and try logging in.

**Comment by b0bst3r** [comment]
No reply to issue within 24 days.

**Comment by barookve** [comment]
Thanks bob, worked me.
